#pragma once

#include <cstdint>

enum class BNETOpcode8 : uint8_t {
    SID_NULL                        = 0x00, // Пустой пакет (подтверждение связи)
    SID_INIT                        = 0x01, // Пустой пакет (подтверждение связи)
    SID_STOPADV                     = 0x02, // Остановка рекламы игры
    SID_GETADVLIST                  = 0x09, // Запрос списка игр (устаревший)
    SID_ENTERCHAT                   = 0x0A, // Вход в чат
    SID_JOINCHANNEL                 = 0x0C, // Присоединение к каналу
    SID_CHATCOMMAND                 = 0x0E, // Команда чата
    SID_CHATEVENT                   = 0x0F, // Событие чата (сообщение)
    SID_CHECKAD                     = 0x15, // Проверка рекламы игры
    SID_PING                        = 0x25, // Проверка пинга
    SID_AUTH_INFO                   = 0x50, // Информация для аутентификации
    SID_AUTH_CHECK                  = 0x51, // Проверка аутентификации
    SID_AUTH_ACCOUNTLOGON           = 0x53, // Запрос на вход в аккаунт
    SID_AUTH_ACCOUNTLOGONPROOF      = 0x54, // Подтверждение входа
    SID_AUTH_ACCOUNTCREATE          = 0x52, // Создание аккаунта
    SID_WARCRAFT_GENERAL            = 0x5A, // W3-специфичные команды
    SID_NETGAMEPORT                 = 0x45, // Порт для игры (UDP)
    SID_FRIENDSLIST                 = 0x65, // Список друзей
    SID_FRIENDSUPDATE               = 0x66, // Обновление статуса друга
    SID_FRIENDSADD                  = 0x67, // Добавление друга
    SID_FRIENDSREMOVE               = 0x68, // Удаление друга
    SID_MESSAGEBOX                  = 0x69, // Всплывающее сообщение
    SID_STARTADVEX3                 = 0x6C, // Реклама игры (расширенная)
    SID_GETADVLISTEX                = 0x75, // Расширенный запрос списка игр
    SID_UDPPINGRESPONSE             = 0x79, // Ответ на UDP-пинг
    SID_CLANMEMBERLIST              = 0x7D, // Список членов клана
    SID_CLANINVITATION              = 0x7F, // Приглашение в клан
    SID_CLANCREATIONINVITATION      = 0x80, // Приглашение в создание клана
    SID_CLANDISBAND                 = 0x81, // Роспуск клана
    SID_CLANMEMBERSTATUSCHANGE      = 0x82, // Изменение статуса члена клана
    SID_CLANREMOVEMEMBER            = 0x85, // Удаление члена клана
    SID_CLANMEMBERINFORMATION       = 0x87, // Информация о члене клана
    SID_CLANRANKCHANGE              = 0x89, // Изменение ранга в клане
    SID_CLANSETMOTD                 = 0x8B, // Установка MOTD (сообщения дня)
    SID_CLANMOTD                    = 0x8C, // Получение MOTD
    SID_CLANMEMBERLISTEXTENDED      = 0x8D, // Расширенный список клана
    SID_CLANMEMBERLISTALL           = 0x8E, // Полный список клана
    SID_CLANMEMBERREMOVED           = 0x90, // Уведомление об удалении из клана
    SID_CLANINVITATIONRESPONSE      = 0x91, // Ответ на приглашение в клан
    SID_CLANINVITATIONREQUEST       = 0x92, // Запрос на приглашение в клан
    SID_CLANINVITATIONREJECT        = 0x93, // Отклонение приглашения в клан
    SID_CLANINVITATIONACCEPT        = 0x94, // Принятие приглашения в клан
    SID_CLANQUITNOTIFY              = 0x95, // Уведомление о выходе из клана
    SID_CLANCHANGECHIEFTAIN         = 0x96, // Смена лидера клана
    SID_CLANCREATECHALLENGE         = 0x97, // Создание кланового вызова
    SID_CLANCREATIONINVITATIONRESPONSE = 0x98, // Ответ на приглашение создать клан
    SID_CLANCREATIONINVITATIONREJECT = 0x99, // Отклонение приглашения создать клан
    SID_CLANCREATIONINVITATIONACCEPT = 0x9A, // Принятие приглашения создать клан
    SID_CLANWARINVITATION           = 0x9B, // Приглашение на клановую войну
    SID_CLANWARINVITATIONRESPONSE   = 0x9C, // Ответ на приглашение на клановую войну
    SID_CLANWARINVITATIONREJECT     = 0x9D, // Отклонение клановой войны
    SID_CLANWARINVITATIONACCEPT     = 0x9E, // Принятие клановой войны
    SID_CLANWARENDED                = 0x9F, // Окончание клановой войны
    SID_CLANWARRESULT               = 0xA0, // Результат клановой войны
    SID_CLANWARPLAYERKICKED         = 0xA1, // Игрок исключён из клановой войны
    SID_CLANWARPLAYERJOINED         = 0xA2, // Игрок присоединился к клановой войне
    SID_CLANWARPLAYERLEFT           = 0xA3, // Игрок покинул клановую войну
    SID_CLANWARPLAYERDISCONNECTED    = 0xA4, // Игрок отключился от клановой войны
    SID_CLANWARPLAYERRECONNECTED     = 0xA5, // Игрок переподключился к клановой войне
    SID_CLANWARPLAYERCHANGEDTEAM    = 0xA6, // Игрок сменил команду в клановой войне
    SID_CLANWARPLAYERCHANGEDRACE    = 0xA7, // Игрок сменил расу в клановой войне
    SID_CLANWARPLAYERCHANGEDCOLOR   = 0xA8, // Игрок сменил цвет в клановой войне
    SID_CLANWARPLAYERCHANGEDHANDICAP = 0xA9, // Игрок сменил фору в клановой войне
    SID_CLANWARPLAYERCHANGEDOBSERVER_CW = 0xAA, // Игрок стал наблюдателем в клановой войне
    SID_CLANWARPLAYERCHANGEDREADY   = 0xAB, // Игрок изменил статус готовности
    SID_CLANWARPLAYERCHANGEDSYNC    = 0xAC, // Игрок изменил статус синхронизации
    SID_CLANWARPLAYERCHANGEDLOADED  = 0xAD, // Игрок загрузился в клановой войне
    SID_CLANWARPLAYERCHANGEDSTARTED = 0xAE, // Игрок начал играть в клановой войне
    SID_CLANWARPLAYERCHANGEDFINISHED = 0xAF, // Игрок закончил клановую войну
    SID_CLANWARPLAYERCHANGEDWINNER  = 0xB0, // Игрок победил в клановой войне
    SID_CLANWARPLAYERCHANGEDLOSER   = 0xB1, // Игрок проиграл в клановой войне
    SID_CLANWARPLAYERCHANGEDDRAW    = 0xB2, // Ничья в клановой войне
    SID_CLANWARPLAYERCHANGEDABORTED = 0xB3, // Клановая война отменена
    SID_CLANWARPLAYERCHANGEDDISCONNECTED = 0xB4, // Игрок отключился
    SID_CLANWARPLAYERCHANGEDRECONNECTED = 0xB5, // Игрок переподключился
    SID_CLANWARPLAYERCHANGEDKICKED  = 0xB6, // Игрок исключён
    SID_CLANWARPLAYERCHANGEDBANNED  = 0xB7, // Игрок забанен
    SID_CLANWARPLAYERCHANGEDMUTED   = 0xB8, // Игрок заглушен
    SID_CLANWARPLAYERCHANGEDUNMUTED = 0xB9, // Игрок разглушен
    SID_CLANWARPLAYERCHANGEDSPEAKER = 0xBA, // Игрок получил право голоса
    SID_CLANWARPLAYERCHANGEDLISTENER = 0xBB, // Игрок стал слушателем
    SID_CLANWARPLAYERCHANGEDDEAFENED = 0xBC, // Игрок лишён звука
    SID_CLANWARPLAYERCHANGEDUNDEAFENED = 0xBD, // Игрок восстановлен
    SID_CLANWARPLAYERCHANGEDVOICE   = 0xBE, // Игрок получил голосовой чат
    SID_CLANWARPLAYERCHANGEDNOVOICE = 0xBF, // Игрок потерял голосовой чат
    SID_CLANWARPLAYERCHANGEDADMIN   = 0xC0, // Игрок получил админ-права
    SID_CLANWARPLAYERCHANGEDUNADMIN = 0xC1, // Игрок потерял админ-права
    SID_CLANWARPLAYERCHANGEDMODERATOR = 0xC2, // Игрок стал модератором
    SID_CLANWARPLAYERCHANGEDUNMODERATOR = 0xC3, // Игрок перестал быть модератором
    SID_CLANWARPLAYERCHANGEDOWNER   = 0xC4, // Игрок стал владельцем
    SID_CLANWARPLAYERCHANGEDUNOWNER = 0xC5, // Игрок перестал быть владельцем
    SID_CLANWARPLAYERCHANGEDCREATOR = 0xC6, // Игрок стал создателем
    SID_CLANWARPLAYERCHANGEDUNCREATOR = 0xC7, // Игрок перестал быть создателем
    SID_CLANWARPLAYERCHANGEDHOST    = 0xC8, // Игрок стал хостом
    SID_CLANWARPLAYERCHANGEDUNHOST  = 0xC9, // Игрок перестал быть хостом
    SID_CLANWARPLAYERCHANGEDPLAYER  = 0xCA, // Игрок стал игроком
    SID_CLANWARPLAYERCHANGEDUNPLAYER = 0xCB, // Игрок перестал быть игроком
    SID_CLANWARPLAYERCHANGEDOBSERVER = 0xCC, // Игрок стал наблюдателем
    SID_CLANWARPLAYERCHANGEDUNOBSERVER = 0xCD, // Игрок перестал быть наблюдателем
    SID_CLANWARPLAYERCHANGEDSPECTATOR = 0xCE, // Игрок стал зрителем
    SID_CLANWARPLAYERCHANGEDUNSPECTATOR = 0xCF, // Игрок перестал быть зрителем
    SID_CLANWARPLAYERCHANGEDBOT     = 0xD0, // Игрок стал ботом
    SID_CLANWARPLAYERCHANGEDUNBOT  = 0xD1, // Игрок перестал быть ботом
    SID_CLANWARPLAYERCHANGEDAI      = 0xD2, // Игрок стал ИИ
    SID_CLANWARPLAYERCHANGEDUNAI    = 0xD3, // Игрок перестал быть ИИ
    SID_CLANWARPLAYERCHANGEDHUMAN   = 0xD4, // Игрок стал человеком
    SID_CLANWARPLAYERCHANGEDUNHUMAN = 0xD5, // Игрок перестал быть человеком
    SID_CLANWARPLAYERCHANGEDCOMPUTER = 0xD6, // Игрок стал компьютером
    SID_CLANWARPLAYERCHANGEDUNCOMPUTER = 0xD7, // Игрок перестал быть компьютером
    SID_CLANWARPLAYERCHANGEDNEUTRAL = 0xD8, // Игрок стал нейтральным
    SID_CLANWARPLAYERCHANGEDUNNEUTRAL = 0xD9, // Игрок перестал быть нейтральным
    SID_CLANWARPLAYERCHANGEDALLY    = 0xDA, // Игрок стал союзником
    SID_CLANWARPLAYERCHANGEDUNALLY  = 0xDB, // Игрок перестал быть союзником
    SID_CLANWARPLAYERCHANGEDENEMY   = 0xDC, // Игрок стал врагом
    SID_CLANWARPLAYERCHANGEDUNENEMY = 0xDD, // Игрок перестал быть врагом
    SID_CLANWARPLAYERCHANGEDFRIEND  = 0xDE, // Игрок стал другом
    SID_CLANWARPLAYERCHANGEDUNFRIEND = 0xDF, // Игрок перестал быть другом
    SID_CLANWARPLAYERCHANGEDFOE     = 0xE0, // Игрок стал противником
    SID_CLANWARPLAYERCHANGEDUNFOE   = 0xE1, // Игрок перестал быть противником
    SID_CLANWARPLAYERCHANGEDME      = 0xE2, // Игрок — это я
    SID_CLANWARPLAYERCHANGEDUNME    = 0xE3, // Игрок — это не я
    SID_CLANWARPLAYERCHANGEDYOU     = 0xE4, // Игрок — это ты
    SID_CLANWARPLAYERCHANGEDUNYOU   = 0xE5, // Игрок — это не ты
    SID_CLANWARPLAYERCHANGEDHE      = 0xE6, // Игрок — это он
    SID_CLANWARPLAYERCHANGEDUNHE    = 0xE7, // Игрок — это не он
    SID_CLANWARPLAYERCHANGEDSHE     = 0xE8, // Игрок — это она
    SID_CLANWARPLAYERCHANGEDUNSHE   = 0xE9, // Игрок — это не она
    SID_CLANWARPLAYERCHANGEDIT      = 0xEA, // Игрок — это оно
    SID_CLANWARPLAYERCHANGEDUNIT    = 0xEB, // Игрок — это не оно
    SID_CLANWARPLAYERCHANGEDWE      = 0xEC, // Игрок — это мы
    SID_CLANWARPLAYERCHANGEDUNWE    = 0xED, // Игрок — это не мы
    SID_CLANWARPLAYERCHANGEDTHEY    = 0xEE, // Игрок — это они
    SID_CLANWARPLAYERCHANGEDUNTHEY  = 0xEF, // Игрок — это не они
    SID_CLANWARPLAYERCHANGEDUS      = 0xF0, // Игрок — это нас
    SID_CLANWARPLAYERCHANGEDUNUS    = 0xF1, // Игрок — это не нас
    SID_CLANWARPLAYERCHANGEDTHEM    = 0xF2, // Игрок — это их
    SID_CLANWARPLAYERCHANGEDUNTHEM  = 0xF3, // Игрок — это не их
    SID_CLANWARPLAYERCHANGEDOUR     = 0xF4, // Игрок — это наш
    SID_CLANWARPLAYERCHANGEDUNOUR   = 0xF5, // Игрок — это не наш
    SID_CLANWARPLAYERCHANGEDYOUR    = 0xF6, // Игрок — это ваш
    SID_CLANWARPLAYERCHANGEDUNYOUR  = 0xF7, // Игрок — это не ваш
    SID_CLANWARPLAYERCHANGEDHIS     = 0xF8, // Игрок — это его
    SID_CLANWARPLAYERCHANGEDUNHIS   = 0xF9, // Игрок — это не его
    SID_CLANWARPLAYERCHANGEDHER     = 0xFA, // Игрок — это её
    SID_CLANWARPLAYERCHANGEDUNHER   = 0xFB, // Игрок — это не её
    SID_CLANWARPLAYERCHANGEDITSS    = 0xFC, // Игрок — это его (нейтр.)
    SID_CLANWARPLAYERCHANGEDUNITSS  = 0xFD, // Игрок — это не его (нейтр.)
    SID_CLANWARPLAYERCHANGEDTHEIR   = 0xFE, // Игрок — это их
    SID_CLANWARPLAYERCHANGEDUNTHEIR = 0xFF, // Игрок — это не их
};