#pragma once

#include <cstdint>

enum class BNETOpcode16 : uint16_t {
    // Базовые пакеты
    W3GS_HEADER = 0x00F7,  // Заголовок W3GS (магическое число)
    W3GS_OUTGOING_KEEPALIVE = 0x0008,  // Keep-alive пакет (поддержка соединения)
    W3GS_CHAT_FROM_HOST = 0x000A,  // Чат-сообщение от хоста
    W3GS_CHAT_TO_HOST = 0x000B,  // Чат-сообщение хосту
    W3GS_SEARCHGAME = 0x0010,  // Поиск игры (устаревший)
    W3GS_GAMEINFO = 0x0012,  // Информация об игре (ответ на поиск)
    W3GS_CREATEGAME = 0x0014,  // Создание игры
    W3GS_REFRESHGAME = 0x0016,  // Обновление информации об игре
    W3GS_DECREATEGAME = 0x0018,  // Удаление игры
    W3GS_PING_FROM_HOST = 0x0025,  // Пинг от хоста
    W3GS_SLOTINFOJOIN = 0x0027,  // Информация о слотах при присоединении
    W3GS_REJECTJOIN = 0x0028,  // Отказ в присоединении к игре
    W3GS_PLAYERINFO = 0x0029,  // Информация об игроке (пинг, имя и т. д.)
    W3GS_PLAYERLEFT = 0x002A,  // Игрок покинул игру
    W3GS_GAMELOADED = 0x002B,  // Игра загружена (все игроки готовы)
    W3GS_SLOTINFO = 0x002C,  // Обновление информации о слотах
    W3GS_COUNTDOWN_START = 0x002D,  // Начало отсчёта перед игрой
    W3GS_COUNTDOWN_END = 0x002E,  // Конец отсчёта (старт игры)
    W3GS_INCOMING_ACTION = 0x002F,  // Входящие игровые действия (пакет игры)
    W3GS_OUTGOING_ACTION = 0x0030,  // Исходящие игровые действия
    W3GS_OUTGOING_KEEPALIVE2 = 0x0031,  // Дополнительный keep-alive
    W3GS_CHAT_TO_ALL = 0x0032,  // Чат для всех игроков
    W3GS_CHAT_TO_ALLIES = 0x0033,  // Чат для союзников
    W3GS_CHAT_TO_OBSERVERS = 0x0034,  // Чат для наблюдателей
    W3GS_CHAT_FIXED = 0x0035,  // Фиксированное сообщение (системное)
    W3GS_DROPREQ = 0x0036,  // Запрос на отключение игрока (лаг)
    W3GS_MAPCHECK = 0x0037,  // Проверка карты
    W3GS_STARTDOWNLOAD = 0x0038,  // Начало загрузки карты
    W3GS_MAPPART = 0x0039,  // Передача части карты
    W3GS_MAPPART_OK = 0x003A,  // Подтверждение получения части карты
    W3GS_MAPPART_ERROR = 0x003B,  // Ошибка передачи части карты
    W3GS_PONG_TO_HOST = 0x003C,  // Ответ на пинг от хоста
    W3GS_INCOMING_ACTION2 = 0x003D,  // Альтернативный пакет действий (W3 1.29+)
    W3GS_OUTGOING_ACTION2 = 0x003E,  // Альтернативный исходящий пакет действий
    W3GS_GAMEEND = 0x003F,  // Завершение игры (результаты)
    W3GS_PLAYERKICKED = 0x0040,  // Игрок был кикнут
    W3GS_GAMELOADED_OTHERS = 0x0041,  // Другие игроки загрузились
    W3GS_OUTGOING_LOADED = 0x0042,  // Подтверждение загрузки игры
    W3GS_OUTGOING_LOADED_OTHERS = 0x0043,  // Другие игроки подтвердили загрузку
    W3GS_OUTGOING_RELOAD = 0x0044,  // Перезагрузка игры (реконнект)
    W3GS_OUTGOING_RELOAD_OTHERS = 0x0045,  // Другие игроки перезагружаются
    W3GS_OUTGOING_SYNC = 0x0046,  // Синхронизация состояния игры
    W3GS_OUTGOING_SYNC_OTHERS = 0x0047,  // Синхронизация других игроков
    W3GS_OUTGOING_CONCEDE = 0x0048,  // Игрок сдаётся
    W3GS_OUTGOING_CONCEDE_OTHERS = 0x0049,  // Другие игроки сдаются
    W3GS_OUTGOING_SAVEGAME = 0x004A,  // Сохранение игры
    W3GS_OUTGOING_SAVEGAME_OTHERS = 0x004B,  // Другие игроки сохраняют игру
    W3GS_OUTGOING_LOADGAME = 0x004C,  // Загрузка сохранённой игры
    W3GS_OUTGOING_LOADGAME_OTHERS = 0x004D,  // Другие игроки загружают игру
    W3GS_OUTGOING_RESTARTGAME = 0x004E,  // Перезапуск игры
    W3GS_OUTGOING_RESTARTGAME_OTHERS = 0x004F, // Другие игроки перезапускают игру
    W3GS_OUTGOING_SWITCHTEAMS = 0x0050,  // Смена команд
    W3GS_OUTGOING_SWITCHTEAMS_OTHERS = 0x0051, // Другие игроки меняют команды
    W3GS_OUTGOING_SWITCHRACES = 0x0052,  // Смена рас
    W3GS_OUTGOING_SWITCHRACES_OTHERS = 0x0053, // Другие игроки меняют расы
    W3GS_OUTGOING_SWITCHHANDICAP = 0x0054,  // Смена форы (handicap)
    W3GS_OUTGOING_SWITCHHANDICAP_OTHERS = 0x0055, // Другие игроки меняют фору
    W3GS_OUTGOING_SWITCHCOLOR = 0x0056,  // Смена цвета
    W3GS_OUTGOING_SWITCHCOLOR_OTHERS = 0x0057, // Другие игроки меняют цвет
    W3GS_OUTGOING_SWITCHCONTROLLER = 0x0058, // Смена контроллера (наблюдатель → игрок)
    W3GS_OUTGOING_SWITCHCONTROLLER_OTHERS = 0x0059, // Другие игроки меняют статус
    W3GS_OUTGOING_SWITCHOPEN = 0x005A,  // Открытие/закрытие слота
    W3GS_OUTGOING_SWITCHOPEN_OTHERS = 0x005B, // Другие игроки открывают/закрывают слоты
    W3GS_OUTGOING_SWITCHCOMPUTER = 0x005C,  // Переключение слота на компьютер
    W3GS_OUTGOING_SWITCHCOMPUTER_OTHERS = 0x005D, // Другие игроки переключают слоты
    W3GS_OUTGOING_SWITCHNEUTRAL = 0x005E,  // Переключение на нейтральный слот
    W3GS_OUTGOING_SWITCHNEUTRAL_OTHERS = 0x005F, // Другие игроки переключают нейтральные слоты
    W3GS_OUTGOING_SWITCHALLY = 0x0060,  // Изменение союзников
    W3GS_OUTGOING_SWITCHALLY_OTHERS = 0x0061, // Другие игроки меняют союзников
    W3GS_OUTGOING_SWITCHENEMY = 0x0062,  // Изменение врагов
    W3GS_OUTGOING_SWITCHENEMY_OTHERS = 0x0063, // Другие игроки меняют врагов
    W3GS_OUTGOING_SWITCHVISION = 0x0064,  // Изменение обзора (наблюдатели)
    W3GS_OUTGOING_SWITCHVISION_OTHERS = 0x0065, // Другие игроки меняют обзор
    W3GS_OUTGOING_SWITCHSHARED = 0x0066,  // Общий контроль
    W3GS_OUTGOING_SWITCHSHARED_OTHERS = 0x0067, // Другие игроки меняют общий контроль
    W3GS_OUTGOING_SWITCHALLIEDVISION = 0x0068, // Общий обзор союзников
    W3GS_OUTGOING_SWITCHALLIEDVISION_OTHERS = 0x0069, // Другие игроки меняют общий обзор
    W3GS_OUTGOING_SWITCHFOG = 0x006A,  // Туман войны
    W3GS_OUTGOING_SWITCHFOG_OTHERS = 0x006B, // Другие игроки меняют туман войны
    W3GS_OUTGOING_SWITCHBLACKMAP = 0x006C,  // Чёрная карта
    W3GS_OUTGOING_SWITCHBLACKMAP_OTHERS = 0x006D, // Другие игроки меняют чёрную карту
    W3GS_OUTGOING_SWITCHSPEED = 0x006E,  // Изменение скорости игры
    W3GS_OUTGOING_SWITCHSPEED_OTHERS = 0x006F, // Другие игроки меняют скорость
    W3GS_OUTGOING_SWITCHLOCKTEAMS = 0x0070, // Блокировка команд
    W3GS_OUTGOING_SWITCHLOCKTEAMS_OTHERS = 0x0071, // Другие игроки блокируют команды
    W3GS_OUTGOING_SWITCHLOCKRACES = 0x0072, // Блокировка рас
    W3GS_OUTGOING_SWITCHLOCKRACES_OTHERS = 0x0073, // Другие игроки блокируют расы
    W3GS_OUTGOING_SWITCHLOCKHANDICAP = 0x0074, // Блокировка форы
    W3GS_OUTGOING_SWITCHLOCKHANDICAP_OTHERS = 0x0075, // Другие игроки блокируют фору
    W3GS_OUTGOING_SWITCHLOCKCOLOR = 0x0076, // Блокировка цвета
    W3GS_OUTGOING_SWITCHLOCKCOLOR_OTHERS = 0x0077, // Другие игроки блокируют цвет
    W3GS_OUTGOING_SWITCHLOCKCONTROLLER = 0x0078, // Блокировка контроллера
    W3GS_OUTGOING_SWITCHLOCKCONTROLLER_OTHERS = 0x0079, // Другие игроки блокируют контроллер
    W3GS_OUTGOING_SWITCHLOCKOPEN = 0x007A, // Блокировка открытия/закрытия слотов
    W3GS_OUTGOING_SWITCHLOCKOPEN_OTHERS = 0x007B, // Другие игроки блокируют слоты
    W3GS_OUTGOING_SWITCHLOCKCOMPUTER = 0x007C, // Блокировка компьютера в слоте
    W3GS_OUTGOING_SWITCHLOCKCOMPUTER_OTHERS = 0x007D, // Другие игроки блокируют компьютеры
    W3GS_OUTGOING_SWITCHLOCKNEUTRAL = 0x007E, // Блокировка нейтральных слотов
    W3GS_OUTGOING_SWITCHLOCKNEUTRAL_OTHERS = 0x007F, // Другие игроки блокируют нейтральные слоты
    W3GS_OUTGOING_SWITCHLOCKALLY = 0x0080, // Блокировка союзников
    W3GS_OUTGOING_SWITCHLOCKALLY_OTHERS = 0x0081, // Другие игроки блокируют союзников
    W3GS_OUTGOING_SWITCHLOCKENEMY = 0x0082, // Блокировка врагов
    W3GS_OUTGOING_SWITCHLOCKENEMY_OTHERS = 0x0083, // Другие игроки блокируют врагов
    W3GS_OUTGOING_SWITCHLOCKVISION = 0x0084, // Блокировка обзора
    W3GS_OUTGOING_SWITCHLOCKVISION_OTHERS = 0x0085, // Другие игроки блокируют обзор
    W3GS_OUTGOING_SWITCHLOCKSHARED = 0x0086, // Блокировка общего контроля
    W3GS_OUTGOING_SWITCHLOCKSHARED_OTHERS = 0x0087, // Другие игроки блокируют общий контроль
    W3GS_OUTGOING_SWITCHLOCKALLIEDVISION = 0x0088, // Блокировка общего обзора союзников
    W3GS_OUTGOING_SWITCHLOCKALLIEDVISION_OTHERS = 0x0089, // Другие игроки блокируют общий обзор
    W3GS_OUTGOING_SWITCHLOCKFOG = 0x008A, // Блокировка тумана войны
    W3GS_OUTGOING_SWITCHLOCKFOG_OTHERS = 0x008B, // Другие игроки блокируют туман войны
    W3GS_OUTGOING_SWITCHLOCKBLACKMAP = 0x008C, // Блокировка чёрной карты
    W3GS_OUTGOING_SWITCHLOCKBLACKMAP_OTHERS = 0x008D, // Другие игроки блокируют чёрную карту
    W3GS_OUTGOING_SWITCHLOCKSPEED = 0x008E, // Блокировка скорости игры
    W3GS_OUTGOING_SWITCHLOCKSPEED_OTHERS = 0x008F, // Другие игроки блокируют скорость
    W3GS_OUTGOING_SWITCHUNLOCKTEAMS = 0x0090, // Разблокировка команд
    W3GS_OUTGOING_SWITCHUNLOCKTEAMS_OTHERS = 0x0091, // Другие игроки разблокируют команды
    W3GS_OUTGOING_SWITCHUNLOCKRACES = 0x0092, // Разблокировка рас
    W3GS_OUTGOING_SWITCHUNLOCKRACES_OTHERS = 0x0093, // Другие игроки разблокируют расы
    W3GS_OUTGOING_SWITCHUNLOCKHANDICAP = 0x0094, // Разблокировка форы
    W3GS_OUTGOING_SWITCHUNLOCKHANDICAP_OTHERS = 0x0095, // Другие игроки разблокируют фору
    W3GS_OUTGOING_SWITCHUNLOCKCOLOR = 0x0096, // Разблокировка цвета
    W3GS_OUTGOING_SWITCHUNLOCKCOLOR_OTHERS = 0x0097, // Другие игроки разблокируют цвет
    W3GS_OUTGOING_SWITCHUNLOCKCONTROLLER = 0x0098, // Разблокировка контроллера
    W3GS_OUTGOING_SWITCHUNLOCKCONTROLLER_OTHERS = 0x0099, // Другие игроки разблокируют контроллер
    W3GS_OUTGOING_SWITCHUNLOCKOPEN = 0x009A, // Разблокировка открытия/закрытия слотов
    W3GS_OUTGOING_SWITCHUNLOCKOPEN_OTHERS = 0x009B, // Другие игроки разблокируют слоты
    W3GS_OUTGOING_SWITCHUNLOCKCOMPUTER = 0x009C, // Разблокировка компьютера в слоте
    W3GS_OUTGOING_SWITCHUNLOCKCOMPUTER_OTHERS = 0x009D, // Другие игроки разблокируют компьютеры
    W3GS_OUTGOING_SWITCHUNLOCKNEUTRAL = 0x009E, // Разблокировка нейтральных слотов
    W3GS_OUTGOING_SWITCHUNLOCKNEUTRAL_OTHERS = 0x009F, // Другие игроки разблокируют нейтральные слоты
    W3GS_OUTGOING_SWITCHUNLOCKALLY = 0x00A0, // Разблокировка союзников
    W3GS_OUTGOING_SWITCHUNLOCKALLY_OTHERS = 0x00A1, // Другие игроки разблокируют союзников
    W3GS_OUTGOING_SWITCHUNLOCKENEMY = 0x00A2, // Разблокировка врагов
    W3GS_OUTGOING_SWITCHUNLOCKENEMY_OTHERS = 0x00A3, // Другие игроки разблокируют врагов
    W3GS_OUTGOING_SWITCHUNLOCKVISION = 0x00A4, // Разблокировка обзора
    W3GS_OUTGOING_SWITCHUNLOCKVISION_OTHERS = 0x00A5, // Другие игроки разблокируют обзор
    W3GS_OUTGOING_SWITCHUNLOCKSHARED = 0x00A6, // Разблокировка общего контроля
    W3GS_OUTGOING_SWITCHUNLOCKSHARED_OTHERS = 0x00A7, // Другие игроки разблокируют общий контроль
    W3GS_OUTGOING_SWITCHUNLOCKALLIEDVISION = 0x00A8, // Разблокировка общего обзора союзников
    W3GS_OUTGOING_SWITCHUNLOCKALLIEDVISION_OTHERS = 0x00A9, // Другие игроки разблокируют общий обзор
    W3GS_OUTGOING_SWITCHUNLOCKFOG = 0x00AA, // Разблокировка тумана войны
    W3GS_OUTGOING_SWITCHUNLOCKFOG_OTHERS = 0x00AB, // Другие игроки разблокируют туман войны
    W3GS_OUTGOING_SWITCHUNLOCKBLACKMAP = 0x00AC, // Разблокировка чёрной карты
    W3GS_OUTGOING_SWITCHUNLOCKBLACKMAP_OTHERS = 0x00AD, // Другие игроки разблокируют чёрную карту
    W3GS_OUTGOING_SWITCHUNLOCKSPEED = 0x00AE, // Разблокировка скорости игры
    W3GS_OUTGOING_SWITCHUNLOCKSPEED_OTHERS = 0x00AF, // Другие игроки разблокируют скорость
    W3GS_OUTGOING_SWITCHRESET = 0x00B0, // Сброс настроек игры
    W3GS_OUTGOING_SWITCHRESET_OTHERS = 0x00B1, // Другие игроки сбрасывают настройки
    W3GS_OUTGOING_SWITCHDEFAULTS = 0x00B2, // Установка настроек по умолчанию
    W3GS_OUTGOING_SWITCHDEFAULTS_OTHERS = 0x00B3, // Другие игроки устанавливают настройки по умолчанию
    W3GS_OUTGOING_SWITCHCANCEL = 0x00B4, // Отмена изменений
    W3GS_OUTGOING_SWITCHCANCEL_OTHERS = 0x00B5, // Другие игроки отменяют изменения
    W3GS_OUTGOING_SWITCHOK = 0x00B6, // Подтверждение изменений
    W3GS_OUTGOING_SWITCHOK_OTHERS = 0x00B7, // Другие игроки подтверждают изменения
    W3GS_OUTGOING_SWITCHAPPLY = 0x00B8, // Применение изменений
    W3GS_OUTGOING_SWITCHAPPLY_OTHERS = 0x00B9, // Другие игроки применяют изменения
    W3GS_OUTGOING_SWITCHCLOSE = 0x00BA, // Закрытие настроек
    W3GS_OUTGOING_SWITCHCLOSE_OTHERS = 0x00BB, // Другие игроки закрывают настройки
    W3GS_OUTGOING_SWITCHOPENLOBBY = 0x00BC, // Открытие лобби
    W3GS_OUTGOING_SWITCHOPENLOBBY_OTHERS = 0x00BD, // Другие игроки открывают лобби
    W3GS_OUTGOING_SWITCHCLOSELOBBY = 0x00BE, // Закрытие лобби
    W3GS_OUTGOING_SWITCHCLOSELOBBY_OTHERS = 0x00BF, // Другие игроки закрывают лобби
    W3GS_OUTGOING_SWITCHSTARTGAME = 0x00C0, // Начало игры
    W3GS_OUTGOING_SWITCHSTARTGAME_OTHERS = 0x00C1, // Другие игроки начинают игру
    W3GS_OUTGOING_SWITCHLEAVEGAME = 0x00C2, // Выход из игры
    W3GS_OUTGOING_SWITCHLEAVEGAME_OTHERS = 0x00C3, // Другие игроки выходят из игры
    W3GS_OUTGOING_SWITCHABORTGAME = 0x00C4, // Отмена игры
    W3GS_OUTGOING_SWITCHABORTGAME_OTHERS = 0x00C5, // Другие игроки отменяют игру
    W3GS_OUTGOING_SWITCHREPLAY = 0x00C6, // Запись реплея
    W3GS_OUTGOING_SWITCHREPLAY_OTHERS = 0x00C7, // Другие игроки записывают реплей
    W3GS_OUTGOING_SWITCHSAVEREPLAY = 0x00C8, // Сохранение реплея
    W3GS_OUTGOING_SWITCHSAVEREPLAY_OTHERS = 0x00C9, // Другие игроки сохраняют реплей
    W3GS_OUTGOING_SWITCHLOADREPLAY = 0x00CA, // Загрузка реплея
    W3GS_OUTGOING_SWITCHLOADREPLAY_OTHERS = 0x00CB, // Другие игроки загружают реплей
    W3GS_OUTGOING_SWITCHPLAYREPLAY = 0x00CC, // Воспроизведение реплея
    W3GS_OUTGOING_SWITCHPLAYREPLAY_OTHERS = 0x00CD, // Другие игроки воспроизводят реплей
    W3GS_OUTGOING_SWITCHPAUSEREPLAY = 0x00CE, // Пауза реплея
    W3GS_OUTGOING_SWITCHPAUSEREPLAY_OTHERS = 0x00CF, // Другие игроки ставят реплей на паузу
    W3GS_OUTGOING_SWITCHRESUMEREPLAY = 0x00D0, // Продолжение реплея
    W3GS_OUTGOING_SWITCHRESUMEREPLAY_OTHERS = 0x00D1, // Другие игроки продолжают реплей
    W3GS_OUTGOING_SWITCHSTOPREPLAY = 0x00D2, // Остановка реплея
    W3GS_OUTGOING_SWITCHSTOPREPLAY_OTHERS = 0x00D3, // Другие игроки останавливают реплей
    W3GS_OUTGOING_SWITCHFASTFORWARDREPLAY = 0x00D4, // Ускорение реплея
    W3GS_OUTGOING_SWITCHFASTFORWARDREPLAY_OTHERS = 0x00D5, // Другие игроки ускоряют реплей
    W3GS_OUTGOING_SWITCHREWINDREPLAY = 0x00D6, // Перемотка реплея назад
    W3GS_OUTGOING_SWITCHREWINDREPLAY_OTHERS = 0x00D7, // Другие игроки перематывают реплей назад
    W3GS_OUTGOING_SWITCHSKIPREPLAY = 0x00D8, // Пропуск части реплея
    W3GS_OUTGOING_SWITCHSKIPREPLAY_OTHERS = 0x00D9, // Другие игроки пропускают часть реплея
    W3GS_OUTGOING_SWITCHSEEKREPLAY = 0x00DA, // Переход к определённому моменту реплея
    W3GS_OUTGOING_SWITCHSEEKREPLAY_OTHERS = 0x00DB, // Другие игроки переходят к моменту реплея
    W3GS_OUTGOING_SWITCHSETREPLAYSPEED = 0x00DC, // Установка скорости реплея
    W3GS_OUTGOING_SWITCHSETREPLAYSPEED_OTHERS = 0x00DD, // Другие игроки устанавливают скорость реплея
    W3GS_OUTGOING_SWITCHGETREPLAYINFO = 0x00DE, // Получение информации о реплее
    W3GS_OUTGOING_SWITCHGETREPLAYINFO_OTHERS = 0x00DF, // Другие игроки получают информацию о реплее
    W3GS_OUTGOING_SWITCHSETREPLAYCOMMENT = 0x00E0, // Установка комментария к реплею
    W3GS_OUTGOING_SWITCHSETREPLAYCOMMENT_OTHERS = 0x00E1, // Другие игроки устанавливают комментарий
    W3GS_OUTGOING_SWITCHGETREPLAYCOMMENT = 0x00E2, // Получение комментария реплея
    W3GS_OUTGOING_SWITCHGETREPLAYCOMMENT_OTHERS = 0x00E3, // Другие игроки получают комментарий
    W3GS_OUTGOING_SWITCHSETREPLAYRATING = 0x00E4, // Установка рейтинга реплея
    W3GS_OUTGOING_SWITCHSETREPLAYRATING_OTHERS = 0x00E5, // Другие игроки устанавливают рейтинг
    W3GS_OUTGOING_SWITCHGETREPLAYRATING = 0x00E6, // Получение рейтинга реплея
    W3GS_OUTGOING_SWITCHGETREPLAYRATING_OTHERS = 0x00E7, // Другие игроки получают рейтинг
    W3GS_OUTGOING_SWITCHSETREPLAYFLAGS = 0x00E8, // Установка флагов реплея
    W3GS_OUTGOING_SWITCHSETREPLAYFLAGS_OTHERS = 0x00E9, // Другие игроки устанавливают флаги
    W3GS_OUTGOING_SWITCHGETREPLAYFLAGS = 0x00EA, // Получение флагов реплея
    W3GS_OUTGOING_SWITCHGETREPLAYFLAGS_OTHERS = 0x00EB, // Другие игроки получают флаги
    W3GS_OUTGOING_SWITCHSETREPLAYMETADATA = 0x00EC, // Установка метаданных реплея
    W3GS_OUTGOING_SWITCHSETREPLAYMETADATA_OTHERS = 0x00ED, // Другие игроки устанавливают метаданные
    W3GS_OUTGOING_SWITCHGETREPLAYMETADATA = 0x00EE, // Получение метаданных реплея
    W3GS_OUTGOING_SWITCHGETREPLAYMETADATA_OTHERS = 0x00EF, // Другие игроки получают метаданные
    W3GS_OUTGOING_SWITCHSETREPLAYKEYFRAMES = 0x00F0, // Установка ключевых кадров реплея
    W3GS_OUTGOING_SWITCHSETREPLAYKEYFRAMES_OTHERS = 0x00F1, // Другие игроки устанавливают ключевые кадры
    W3GS_OUTGOING_SWITCHGETREPLAYKEYFRAMES = 0x00F2, // Получение ключевых кадров реплея
    W3GS_OUTGOING_SWITCHGETREPLAYKEYFRAMES_OTHERS = 0x00F3, // Другие игроки получают ключевые кадры
    W3GS_OUTGOING_SWITCHSETREPLAYCHECKSUM = 0x00F4, // Установка контрольной суммы реплея
    W3GS_OUTGOING_SWITCHSETREPLAYCHECKSUM_OTHERS = 0x00F5, // Другие игроки устанавливают контрольную сумму
    W3GS_OUTGOING_SWITCHGETREPLAYCHECKSUM = 0x00F6, // Получение контрольной суммы реплея
    W3GS_OUTGOING_SWITCHGETREPLAYCHECKSUM_OTHERS = 0x00F7, // Другие игроки получают контрольную сумму
    W3GS_OUTGOING_SWITCHSETREPLAYCRC = 0x00F8, // Установка CRC реплея
    W3GS_OUTGOING_SWITCHSETREPLAYCRC_OTHERS = 0x00F9, // Другие игроки устанавливают CRC
    W3GS_OUTGOING_SWITCHGETREPLAYCRC = 0x00FA, // Получение CRC реплея
    W3GS_OUTGOING_SWITCHGETREPLAYCRC_OTHERS = 0x00FB, // Другие игроки получают CRC
    W3GS_OUTGOING_SWITCHSETREPLAYHASH = 0x00FC, // Установка хеша реплея
    W3GS_OUTGOING_SWITCHSETREPLAYHASH_OTHERS = 0x00FD, // Другие игроки устанавливают хеш
    W3GS_OUTGOING_SWITCHGETREPLAYHASH = 0x00FE, // Получение хеша реплея
    W3GS_OUTGOING_SWITCHGETREPLAYHASH_OTHERS = 0x00FF, // Другие игроки получают хеш
    W3GS_OUTGOING_SWITCHSETREPLAYSIGNATURE = 0x0100, // Установка подписи реплея
    W3GS_OUTGOING_SWITCHSETREPLAYSIGNATURE_OTHERS = 0x0101, // Другие игроки устанавливают подпись
    W3GS_OUTGOING_SWITCHGETREPLAYSIGNATURE = 0x0102, // Получение подписи реплея
    W3GS_OUTGOING_SWITCHGETREPLAYSIGNATURE_OTHERS = 0x0103, // Другие игроки получают подпись
    W3GS_OUTGOING_SWITCHSETREPLAYTAG = 0x0104, // Установка тега реплея
    W3GS_OUTGOING_SWITCHSETREPLAYTAG_OTHERS = 0x0105, // Другие игроки устанавливают тег
    W3GS_OUTGOING_SWITCHGETREPLAYTAG = 0x0106, // Получение тега реплея
    W3GS_OUTGOING_SWITCHGETREPLAYTAG_OTHERS = 0x0107, // Другие игроки получают тег
    W3GS_OUTGOING_SWITCHSETREPLAYTAGS = 0x0108, // Установка тегов реплея
    W3GS_OUTGOING_SWITCHSETREPLAYTAGS_OTHERS = 0x0109, // Другие игроки устанавливают теги
    W3GS_OUTGOING_SWITCHGETREPLAYTAGS = 0x010A, // Получение тегов реплея
    W3GS_OUTGOING_SWITCHGETREPLAYTAGS_OTHERS = 0x010B, // Другие игроки получают теги
    W3GS_OUTGOING_SWITCHSETREPLAYLABEL = 0x010C, // Установка метки реплея
    W3GS_OUTGOING_SWITCHSETREPLAYLABEL_OTHERS = 0x010D, // Другие игроки устанавливают метку
    W3GS_OUTGOING_SWITCHGETREPLAYLABEL = 0x010E, // Получение метки реплея
    W3GS_OUTGOING_SWITCHGETREPLAYLABEL_OTHERS = 0x010F, // Другие игроки получают метку
    W3GS_OUTGOING_SWITCHSETREPLAYLABELS = 0x0110, // Установка меток реплея
    W3GS_OUTGOING_SWITCHSETREPLAYLABELS_OTHERS = 0x0111, // Другие игроки устанавливают метки
    W3GS_OUTGOING_SWITCHGETREPLAYLABELS = 0x0112, // Получение меток реплея
    W3GS_OUTGOING_SWITCHGETREPLAYLABELS_OTHERS = 0x0113, // Другие игроки получают метки
    W3GS_OUTGOING_SWITCHSETREPLAYDESCRIPTION = 0x0114, // Установка описания реплея
    W3GS_OUTGOING_SWITCHSETREPLAYDESCRIPTION_OTHERS = 0x0115, // Другие игроки устанавливают описание
    W3GS_OUTGOING_SWITCHGETREPLAYDESCRIPTION = 0x0116, // Получение описания реплея
    W3GS_OUTGOING_SWITCHGETREPLAYDESCRIPTION_OTHERS = 0x0117, // Другие игроки получают описание
    W3GS_OUTGOING_SWITCHSETREPLAYDESCRIPTIONS = 0x0118, // Установка описаний реплея
    W3GS_OUTGOING_SWITCHSETREPLAYDESCRIPTIONS_OTHERS = 0x0119, // Другие игроки устанавливают описания
    W3GS_OUTGOING_SWITCHGETREPLAYDESCRIPTIONS = 0x011A, // Получение описаний реплея
    W3GS_OUTGOING_SWITCHGETREPLAYDESCRIPTIONS_OTHERS = 0x011B, // Другие игроки получают описания
    W3GS_OUTGOING_SWITCHSETREPLAYFILENAME = 0x011C, // Установка имени файла реплея
    W3GS_OUTGOING_SWITCHSETREPLAYFILENAME_OTHERS = 0x011D, // Другие игроки устанавливают имя файла
    W3GS_OUTGOING_SWITCHGETREPLAYFILENAME = 0x011E, // Получение имени файла реплея
    W3GS_OUTGOING_SWITCHGETREPLAYFILENAME_OTHERS = 0x011F, // Другие игроки получают имя файла
    W3GS_OUTGOING_SWITCHSETREPLAYFILENAMES = 0x0120, // Установка имён файлов реплеев
    W3GS_OUTGOING_SWITCHSETREPLAYFILENAMES_OTHERS = 0x0121, // Другие игроки устанавливают имена файлов
    W3GS_OUTGOING_SWITCHGETREPLAYFILENAMES = 0x0122, // Получение имён файлов реплеев
    W3GS_OUTGOING_SWITCHGETREPLAYFILENAMES_OTHERS = 0x0123, // Другие игроки получают имена файлов
    W3GS_OUTGOING_SWITCHSETREPLAYFILEPATH = 0x0124, // Установка пути к файлу реплея
    W3GS_OUTGOING_SWITCHSETREPLAYFILEPATH_OTHERS = 0x0125, // Другие игроки устанавливают путь
    W3GS_OUTGOING_SWITCHGETREPLAYFILEPATH = 0x0126, // Получение пути к файлу реплея
    W3GS_OUTGOING_SWITCHGETREPLAYFILEPATH_OTHERS = 0x0127, // Другие игроки получают путь
    W3GS_OUTGOING_SWITCHSETREPLAYFILEPATHS = 0x0128, // Установка путей к файлам реплеев
    W3GS_OUTGOING_SWITCHSETREPLAYFILEPATHS_OTHERS = 0x0129, // Другие игроки устанавливают пути
    W3GS_OUTGOING_SWITCHGETREPLAYFILEPATHS = 0x012A, // Получение путей к файлам реплеев
    W3GS_OUTGOING_SWITCHGETREPLAYFILEPATHS_OTHERS = 0x012B, // Другие игроки получают пути
    W3GS_OUTGOING_SWITCHSETREPLAYFILE = 0x012C, // Установка файла реплея
    W3GS_OUTGOING_SWITCHSETREPLAYFILE_OTHERS = 0x012D, // Другие игроки устанавливают файл
    W3GS_OUTGOING_SWITCHGETREPLAYFILE = 0x012E, // Получение файла реплея
    W3GS_OUTGOING_SWITCHGETREPLAYFILE_OTHERS = 0x012F, // Другие игроки получают файл
    W3GS_OUTGOING_SWITCHSETREPLAYFILES = 0x0130, // Установка файлов реплеев
    W3GS_OUTGOING_SWITCHSETREPLAYFILES_OTHERS = 0x0131, // Другие игроки устанавливают файлы
    W3GS_OUTGOING_SWITCHGETREPLAYFILES = 0x0132, // Получение файлов реплеев
    W3GS_OUTGOING_SWITCHGETREPLAYFILES_OTHERS = 0x0133, // Другие игроки получают файлы
    W3GS_OUTGOING_SWITCHSETREPLAYFOLDER = 0x0134, // Установка папки реплеев
    W3GS_OUTGOING_SWITCHSETREPLAYFOLDER_OTHERS = 0x0135, // Другие игроки устанавливают папку
    W3GS_OUTGOING_SWITCHGETREPLAYFOLDER = 0x0136, // Получение папки реплеев
    W3GS_OUTGOING_SWITCHGETREPLAYFOLDER_OTHERS = 0x0137, // Другие игроки получают папку
    W3GS_OUTGOING_SWITCHSETREPLAYFOLDERS = 0x0138, // Установка папок реплеев
    W3GS_OUTGOING_SWITCHSETREPLAYFOLDERS_OTHERS = 0x0139, // Другие игроки устанавливают папки
    W3GS_OUTGOING_SWITCHGETREPLAYFOLDERS = 0x013A, // Получение папок реплеев
    W3GS_OUTGOING_SWITCHGETREPLAYFOLDERS_OTHERS = 0x013B, // Другие игроки получают папки
    W3GS_OUTGOING_SWITCHSETREPLAYDIRECTORY = 0x013C, // Установка директории реплеев
    W3GS_OUTGOING_SWITCHSETREPLAYDIRECTORY_OTHERS = 0x013D, // Другие игроки устанавливают директорию
    W3GS_OUTGOING_SWITCHGETREPLAYDIRECTORY = 0x013E, // Получение директории реплеев
    W3GS_OUTGOING_SWITCHGETREPLAYDIRECTORY_OTHERS = 0x013F, // Другие игроки получают директорию
    W3GS_OUTGOING_SWITCHSETREPLAYDIRECTORIES = 0x0140, // Установка директорий реплеев
    W3GS_OUTGOING_SWITCHSETREPLAYDIRECTORIES_OTHERS = 0x0141, // Другие игроки устанавливают директории
    W3GS_OUTGOING_SWITCHGETREPLAYDIRECTORIES = 0x0142, // Получение директорий реплеев
    W3GS_OUTGOING_SWITCHGETREPLAYDIRECTORIES_OTHERS = 0x0143, // Другие игроки получают директории
    W3GS_OUTGOING_SWITCHSETREPLAYLOCATION = 0x0144, // Установка расположения реплея
    W3GS_OUTGOING_SWITCHSETREPLAYLOCATION_OTHERS = 0x0145, // Другие игроки устанавливают расположение
    W3GS_OUTGOING_SWITCHGETREPLAYLOCATION = 0x0146, // Получение расположения реплея
    W3GS_OUTGOING_SWITCHGETREPLAYLOCATION_OTHERS = 0x0147, // Другие игроки получают расположение
    W3GS_OUTGOING_SWITCHSETREPLAYLOCATIONS = 0x0148, // Установка расположений реплеев
    W3GS_OUTGOING_SWITCHSETREPLAYLOCATIONS_OTHERS = 0x0149, // Другие игроки устанавливают расположения
    W3GS_OUTGOING_SWITCHGETREPLAYLOCATIONS = 0x014A, // Получение расположений реплеев
    W3GS_OUTGOING_SWITCHGETREPLAYLOCATIONS_OTHERS = 0x014B, // Другие игроки получают расположения
    W3GS_OUTGOING_SWITCHSETREPLAYURL = 0x014C, // Установка URL реплея
    W3GS_OUTGOING_SWITCHSETREPLAYURL_OTHERS = 0x014D, // Другие игроки устанавливают URL
    W3GS_OUTGOING_SWITCHGETREPLAYURL = 0x014E, // Получение URL реплея
    W3GS_OUTGOING_SWITCHGETREPLAYURL_OTHERS = 0x014F, // Другие игроки получают URL
    W3GS_OUTGOING_SWITCHSETREPLAYURLS = 0x0150, // Установка URL реплеев
    W3GS_OUTGOING_SWITCHSETREPLAYURLS_OTHERS = 0x0151, // Другие игроки устанавливают URL
    W3GS_OUTGOING_SWITCHGETREPLAYURLS = 0x0152, // Получение URL реплеев
    W3GS_OUTGOING_SWITCHGETREPLAYURLS_OTHERS = 0x0153, // Другие игроки получают URL
    W3GS_OUTGOING_SWITCHSETREPLAYURI = 0x0154, // Установка URI реплея
    W3GS_OUTGOING_SWITCHSETREPLAYURI_OTHERS = 0x0155, // Другие игроки устанавливают URI
    W3GS_OUTGOING_SWITCHGETREPLAYURI = 0x0156, // Получение URI реплея
    W3GS_OUTGOING_SWITCHGETREPLAYURI_OTHERS = 0x0157, // Другие игроки получают URI
    W3GS_OUTGOING_SWITCHSETREPLAYURIS = 0x0158, // Установка URI реплеев
    W3GS_OUTGOING_SWITCHSETREPLAYURIS_OTHERS = 0x0159, // Другие игроки устанавливают URI
    W3GS_OUTGOING_SWITCHGETREPLAYURIS = 0x015A, // Получение URI реплеев
    W3GS_OUTGOING_SWITCHGETREPLAYURIS_OTHERS = 0x015B, // Другие игроки получают URI
    W3GS_OUTGOING_SWITCHSETREPLAYLINK = 0x015C, // Установка ссылки на реплей
    W3GS_OUTGOING_SWITCHSETREPLAYLINK_OTHERS = 0x015D, // Другие игроки устанавливают ссылку
    W3GS_OUTGOING_SWITCHGETREPLAYLINK = 0x015E, // Получение ссылки на реплей
    W3GS_OUTGOING_SWITCHGETREPLAYLINK_OTHERS = 0x015F, // Другие игроки получают ссылку
    W3GS_OUTGOING_SWITCHSETREPLAYLINKS = 0x0160, // Установка ссылок на реплеи
    W3GS_OUTGOING_SWITCHSETREPLAYLINKS_OTHERS = 0x0161, // Другие игроки устанавливают ссылки
    W3GS_OUTGOING_SWITCHGETREPLAYLINKS = 0x0162, // Получение ссылок на реплеи
    W3GS_OUTGOING_SWITCHGETREPLAYLINKS_OTHERS = 0x0163, // Другие игроки получают ссылки
    W3GS_OUTGOING_SWITCHSETREPLAYREFERENCE = 0x0164, // Установка ссылки на реплей
    W3GS_OUTGOING_SWITCHSETREPLAYREFERENCE_OTHERS = 0x0165, // Другие игроки устанавливают ссылку
    W3GS_OUTGOING_SWITCHGETREPLAYREFERENCE = 0x0166, // Получение ссылки на реплей
    W3GS_OUTGOING_SWITCHGETREPLAYREFERENCE_OTHERS = 0x0167, // Другие игроки получают ссылку
    W3GS_OUTGOING_SWITCHSETREPLAYREFERENCES = 0x0168, // Установка ссылок на реплеи
    W3GS_OUTGOING_SWITCHSETREPLAYREFERENCES_OTHERS = 0x0169, // Другие игроки устанавливают ссылки
    W3GS_OUTGOING_SWITCHGETREPLAYREFERENCES = 0x016A, // Получение ссылок на реплеи
    W3GS_OUTGOING_SWITCHGETREPLAYREFERENCES_OTHERS = 0x016B, // Другие игроки получают ссылки
    W3GS_OUTGOING_SWITCHSETREPLAYSOURCE = 0x016C, // Установка источника реплея
    W3GS_OUTGOING_SWITCHSETREPLAYSOURCE_OTHERS = 0x016D, // Другие игроки устанавливают источник
    W3GS_OUTGOING_SWITCHGETREPLAYSOURCE = 0x016E, // Получение источника реплея
    W3GS_OUTGOING_SWITCHGETREPLAYSOURCE_OTHERS = 0x016F, // Другие игроки получают источник
    W3GS_OUTGOING_SWITCHSETREPLAYSOURCES = 0x0170, // Установка источников реплеев
    W3GS_OUTGOING_SWITCHSETREPLAYSOURCES_OTHERS = 0x0171, // Другие игроки устанавливают источники
    W3GS_OUTGOING_SWITCHGETREPLAYSOURCES = 0x0172, // Получение источников реплеев
    W3GS_OUTGOING_SWITCHGETREPLAYSOURCES_OTHERS = 0x0173, // Другие игроки получают источники
    W3GS_OUTGOING_SWITCHSETREPLAYTARGET = 0x0174, // Установка цели реплея
    W3GS_OUTGOING_SWITCHSETREPLAYTARGET_OTHERS = 0x0175, // Другие игроки устанавливают цель
    W3GS_OUTGOING_SWITCHGETREPLAYTARGET = 0x0176, // Получение цели реплея
    W3GS_OUTGOING_SWITCHGETREPLAYTARGET_OTHERS = 0x0177, // Другие игроки получают цель
    W3GS_OUTGOING_SWITCHSETREPLAYTARGETS = 0x0178, // Установка целей реплеев
    W3GS_OUTGOING_SWITCHSETREPLAYTARGETS_OTHERS = 0x0179, // Другие игроки устанавливают цели
    W3GS_OUTGOING_SWITCHGETREPLAYTARGETS = 0x017A, // Получение целей реплеев
    W3GS_OUTGOING_SWITCHGETREPLAYTARGETS_OTHERS = 0x017B, // Другие игроки получают цели
    W3GS_OUTGOING_SWITCHSETREPLAYDESTINATION = 0x017C, // Установка назначения реплея
    W3GS_OUTGOING_SWITCHSETREPLAYDESTINATION_OTHERS = 0x017D, // Другие игроки устанавливают назначение
    W3GS_OUTGOING_SWITCHGETREPLAYDESTINATION = 0x017E, // Получение назначения реплея
    W3GS_OUTGOING_SWITCHGETREPLAYDESTINATION_OTHERS = 0x017F, // Другие игроки получают назначение
    W3GS_OUTGOING_SWITCHSETREPLAYDESTINATIONS = 0x0180, // Установка назначений реплеев
    W3GS_OUTGOING_SWITCHSETREPLAYDESTINATIONS_OTHERS = 0x0181, // Другие игроки устанавливают назначения
    W3GS_OUTGOING_SWITCHGETREPLAYDESTINATIONS = 0x0182, // Получение назначений реплеев
    W3GS_OUTGOING_SWITCHGETREPLAYDESTINATIONS_OTHERS = 0x0183, // Другие игроки получают назначения
    W3GS_OUTGOING_SWITCHSETREPLAYENDPOINT = 0x0184, // Установка конечной точки реплея
    W3GS_OUTGOING_SWITCHSETREPLAYENDPOINT_OTHERS = 0x0185, // Другие игроки устанавливают конечную точку
    W3GS_OUTGOING_SWITCHGETREPLAYENDPOINT = 0x0186, // Получение конечной точки реплея
    W3GS_OUTGOING_SWITCHGETREPLAYENDPOINT_OTHERS = 0x0187, // Другие игроки получают конечную точку
    W3GS_OUTGOING_SWITCHSETREPLAYENDPOINTS = 0x0188, // Установка конечных точек реплеев
    W3GS_OUTGOING_SWITCHSETREPLAYENDPOINTS_OTHERS = 0x0189, // Другие игроки устанавливают конечные точки
    W3GS_OUTGOING_SWITCHGETREPLAYENDPOINTS = 0x018A, // Получение конечных точек реплеев
    W3GS_OUTGOING_SWITCHGETREPLAYENDPOINTS_OTHERS = 0x018B, // Другие игроки получают конечные точки
    W3GS_OUTGOING_SWITCHSETREPLAYADDRESS = 0x018C, // Установка адреса реплея
    W3GS_OUTGOING_SWITCHSETREPLAYADDRESS_OTHERS = 0x018D, // Другие игроки устанавливают адрес
    W3GS_OUTGOING_SWITCHGETREPLAYADDRESS = 0x018E, // Получение адреса реплея
    W3GS_OUTGOING_SWITCHGETREPLAYADDRESS_OTHERS = 0x018F, // Другие игроки получают адрес
    W3GS_OUTGOING_SWITCHSETREPLAYADDRESSES = 0x0190, // Установка адресов реплеев
    W3GS_OUTGOING_SWITCHSETREPLAYADDRESSES_OTHERS = 0x0191, // Другие игроки устанавливают адреса
    W3GS_OUTGOING_SWITCHGETREPLAYADDRESSES = 0x0192, // Получение адресов реплеев
    W3GS_OUTGOING_SWITCHGETREPLAYADDRESSES_OTHERS = 0x0193, // Другие игроки получают адреса
    W3GS_OUTGOING_SWITCHSETREPLAYPORT = 0x0194, // Установка порта реплея
    W3GS_OUTGOING_SWITCHSETREPLAYPORT_OTHERS = 0x0195, // Другие игроки устанавливают порт
    W3GS_OUTGOING_SWITCHGETREPLAYPORT = 0x0196, // Получение порта реплея
    W3GS_OUTGOING_SWITCHGETREPLAYPORT_OTHERS = 0x0197, // Другие игроки получают порт
    W3GS_OUTGOING_SWITCHSETREPLAYPORTS = 0x0198, // Установка портов реплеев
    W3GS_OUTGOING_SWITCHSETREPLAYPORTS_OTHERS = 0x0199, // Другие игроки устанавливают порты
    W3GS_OUTGOING_SWITCHGETREPLAYPORTS = 0x019A, // Получение портов реплеев
    W3GS_OUTGOING_SWITCHGETREPLAYPORTS_OTHERS = 0x019B, // Другие игроки получают порты
    W3GS_OUTGOING_SWITCHSETREPLAYHOST = 0x019C, // Установка хоста реплея
    W3GS_OUTGOING_SWITCHSETREPLAYHOST_OTHERS = 0x019D, // Другие игроки устанавливают хост
    W3GS_OUTGOING_SWITCHGETREPLAYHOST = 0x019E, // Получение хоста реплея
    W3GS_OUTGOING_SWITCHGETREPLAYHOST_OTHERS = 0x019F, // Другие игроки получают хост
    W3GS_OUTGOING_SWITCHSETREPLAYHOSTS = 0x01A0, // Установка хостов реплеев
    W3GS_OUTGOING_SWITCHSETREPLAYHOSTS_OTHERS = 0x01A1, // Другие игроки устанавливают хосты
    W3GS_OUTGOING_SWITCHGETREPLAYHOSTS = 0x01A2, // Получение хостов реплеев
    W3GS_OUTGOING_SWITCHGETREPLAYHOSTS_OTHERS = 0x01A3, // Другие игроки получают хосты
    W3GS_OUTGOING_SWITCHSETREPLAYSERVER = 0x01A4, // Установка сервера реплея
    W3GS_OUTGOING_SWITCHSETREPLAYSERVER_OTHERS = 0x01A5, // Другие игроки устанавливают сервер
    W3GS_OUTGOING_SWITCHGETREPLAYSERVER = 0x01A6, // Получение сервера реплея
    W3GS_OUTGOING_SWITCHGETREPLAYSERVER_OTHERS = 0x01A7, // Другие игроки получают сервер
    W3GS_OUTGOING_SWITCHSETREPLAYSERVERS = 0x01A8, // Установка серверов реплеев
    W3GS_OUTGOING_SWITCHSETREPLAYSERVERS_OTHERS = 0x01A9, // Другие игроки устанавливают серверы
    W3GS_OUTGOING_SWITCHGETREPLAYSERVERS = 0x01AA, // Получение серверов реплеев
    W3GS_OUTGOING_SWITCHGETREPLAYSERVERS_OTHERS = 0x01AB, // Другие игроки получают серверы
    W3GS_OUTGOING_SWITCHSETREPLAYCLIENT = 0x01AC, // Установка клиента реплея
    W3GS_OUTGOING_SWITCHSETREPLAYCLIENT_OTHERS = 0x01AD, // Другие игроки устанавливают клиент
    W3GS_OUTGOING_SWITCHGETREPLAYCLIENT = 0x01AE, // Получение клиента реплея
    W3GS_OUTGOING_SWITCHGETREPLAYCLIENT_OTHERS = 0x01AF, // Другие игроки получают клиент
    W3GS_OUTGOING_SWITCHSETREPLAYCLIENTS = 0x01B0, // Установка клиентов реплеев
    W3GS_OUTGOING_SWITCHSETREPLAYCLIENTS_OTHERS = 0x01B1, // Другие игроки устанавливают клиенты
    W3GS_OUTGOING_SWITCHGETREPLAYCLIENTS = 0x01B2, // Получение клиентов реплеев
    W3GS_OUTGOING_SWITCHGETREPLAYCLIENTS_OTHERS = 0x01B3, // Другие игроки получают клиенты
    W3GS_OUTGOING_SWITCHSETREPLAYPEER = 0x01B4, // Установка пира реплея
    W3GS_OUTGOING_SWITCHSETREPLAYPEER_OTHERS = 0x01B5, // Другие игроки устанавливают пира
    W3GS_OUTGOING_SWITCHGETREPLAYPEER = 0x01B6, // Получение пира реплея
    W3GS_OUTGOING_SWITCHGETREPLAYPEER_OTHERS = 0x01B7, // Другие игроки получают пира
    W3GS_OUTGOING_SWITCHSETREPLAYPEERS = 0x01B8, // Установка пиров реплеев
    W3GS_OUTGOING_SWITCHSETREPLAYPEERS_OTHERS = 0x01B9, // Другие игроки устанавливают пиров
    W3GS_OUTGOING_SWITCHGETREPLAYPEERS = 0x01BA, // Получение пиров реплеев
    W3GS_OUTGOING_SWITCHGETREPLAYPEERS_OTHERS = 0x01BB, // Другие игроки получают пиров
    W3GS_OUTGOING_SWITCHSETREPLAYNODE = 0x01BC, // Установка узла реплея
    W3GS_OUTGOING_SWITCHSETREPLAYNODE_OTHERS = 0x01BD, // Другие игроки устанавливают узел
    W3GS_OUTGOING_SWITCHGETREPLAYNODE = 0x01BE, // Получение узла реплея
    W3GS_OUTGOING_SWITCHGETREPLAYNODE_OTHERS = 0x01BF, // Другие игроки получают узел
    W3GS_OUTGOING_SWITCHSETREPLAYNODES = 0x01C0, // Установка узлов реплеев
    W3GS_OUTGOING_SWITCHSETREPLAYNODES_OTHERS = 0x01C1, // Другие игроки устанавливают узлы
    W3GS_OUTGOING_SWITCHGETREPLAYNODES = 0x01C2, // Получение узлов реплеев
    W3GS_OUTGOING_SWITCHGETREPLAYNODES_OTHERS = 0x01C3, // Другие игроки получают узлы
    W3GS_OUTGOING_SWITCHSETREPLAYGATEWAY = 0x01C4, // Установка шлюза реплея
    W3GS_OUTGOING_SWITCHSETREPLAYGATEWAY_OTHERS = 0x01C5, // Другие игроки устанавливают шлюз
    W3GS_OUTGOING_SWITCHGETREPLAYGATEWAY = 0x01C6, // Получение шлюза реплея
    W3GS_OUTGOING_SWITCHGETREPLAYGATEWAY_OTHERS = 0x01C7, // Другие игроки получают шлюз
    W3GS_OUTGOING_SWITCHSETREPLAYGATEWAYS = 0x01C8, // Установка шлюзов реплеев
    W3GS_OUTGOING_SWITCHSETREPLAYGATEWAYS_OTHERS = 0x01C9, // Другие игроки устанавливают шлюзы
    W3GS_OUTGOING_SWITCHGETREPLAYGATEWAYS = 0x01CA, // Получение шлюзов реплеев
    W3GS_OUTGOING_SWITCHGETREPLAYGATEWAYS_OTHERS = 0x01CB, // Другие игроки получают шлюзы
    W3GS_OUTGOING_SWITCHSETREPLAYROUTER = 0x01CC, // Установка маршрутизатора реплея
    W3GS_OUTGOING_SWITCHSETREPLAYROUTER_OTHERS = 0x01CD, // Другие игроки устанавливают маршрутизатор
    W3GS_OUTGOING_SWITCHGETREPLAYROUTER = 0x01CE, // Получение маршрутизатора реплея
    W3GS_OUTGOING_SWITCHGETREPLAYROUTER_OTHERS = 0x01CF, // Другие игроки получают маршрутизатор
    W3GS_OUTGOING_SWITCHSETREPLAYROUTERS = 0x01D0, // Установка маршрутизаторов реплеев
    W3GS_OUTGOING_SWITCHSETREPLAYROUTERS_OTHERS = 0x01D1, // Другие игроки устанавливают маршрутизаторы
    W3GS_OUTGOING_SWITCHGETREPLAYROUTERS = 0x01D2, // Получение маршрутизаторов реплеев
    W3GS_OUTGOING_SWITCHGETREPLAYROUTERS_OTHERS = 0x01D3, // Другие игроки получают маршрутизаторы
    W3GS_OUTGOING_SWITCHSETREPLAYSWITCH = 0x01D4, // Установка коммутатора реплея
    W3GS_OUTGOING_SWITCHSETREPLAYSWITCH_OTHERS = 0x01D5, // Другие игроки устанавливают коммутатор
    W3GS_OUTGOING_SWITCHGETREPLAYSWITCH = 0x01D6, // Получение коммутатора реплея
    W3GS_OUTGOING_SWITCHGETREPLAYSWITCH_OTHERS = 0x01D7, // Другие игроки получают коммутатор
    W3GS_OUTGOING_SWITCHSETREPLAYSWITCHES = 0x01D8, // Установка коммутаторов реплеев
    W3GS_OUTGOING_SWITCHSETREPLAYSWITCHES_OTHERS = 0x01D9, // Другие игроки устанавливают коммутаторы
    W3GS_OUTGOING_SWITCHGETREPLAYSWITCHES = 0x01DA, // Получение коммутаторов реплеев
    W3GS_OUTGOING_SWITCHGETREPLAYSWITCHES_OTHERS = 0x01DB, // Другие игроки получают коммутаторы
    W3GS_OUTGOING_SWITCHSETREPLAYHUB = 0x01DC, // Установка хаба реплея
    W3GS_OUTGOING_SWITCHSETREPLAYHUB_OTHERS = 0x01DD, // Другие игроки устанавливают хаб
    W3GS_OUTGOING_SWITCHGETREPLAYHUB = 0x01DE, // Получение хаба реплея
    W3GS_OUTGOING_SWITCHGETREPLAYHUB_OTHERS = 0x01DF, // Другие игроки получают хаб
    W3GS_OUTGOING_SWITCHSETREPLAYHUBS = 0x01E0, // Установка хабов реплеев
    W3GS_OUTGOING_SWITCHSETREPLAYHUBS_OTHERS = 0x01E1, // Другие игроки устанавливают хабы
    W3GS_OUTGOING_SWITCHGETREPLAYHUBS = 0x01E2, // Получение хабов реплеев
    W3GS_OUTGOING_SWITCHGETREPLAYHUBS_OTHERS = 0x01E3, // Другие игроки получают хабы
    W3GS_OUTGOING_SWITCHSETREPLAYBRIDGE = 0x01E4, // Установка моста реплея
    W3GS_OUTGOING_SWITCHSETREPLAYBRIDGE_OTHERS = 0x01E5, // Другие игроки устанавливают мост
    W3GS_OUTGOING_SWITCHGETREPLAYBRIDGE = 0x01E6, // Получение моста реплея
    W3GS_OUTGOING_SWITCHGETREPLAYBRIDGE_OTHERS = 0x01E7, // Другие игроки получают мост
    W3GS_OUTGOING_SWITCHSETREPLAYBRIDGES = 0x01E8, // Установка мостов реплеев
    W3GS_OUTGOING_SWITCHSETREPLAYBRIDGES_OTHERS = 0x01E9, // Другие игроки устанавливают мосты
    W3GS_OUTGOING_SWITCHGETREPLAYBRIDGES = 0x01EA, // Получение мостов реплеев
    W3GS_OUTGOING_SWITCHGETREPLAYBRIDGES_OTHERS = 0x01EB, // Другие игроки получают мосты
    W3GS_OUTGOING_SWITCHSETREPLAYTUNNEL = 0x01EC, // Установка туннеля реплея
    W3GS_OUTGOING_SWITCHSETREPLAYTUNNEL_OTHERS = 0x01ED, // Другие игроки устанавливают туннель
    W3GS_OUTGOING_SWITCHGETREPLAYTUNNEL = 0x01EE, // Получение туннеля реплея
    W3GS_OUTGOING_SWITCHGETREPLAYTUNNEL_OTHERS = 0x01EF, // Другие игроки получают туннель
    W3GS_OUTGOING_SWITCHSETREPLAYTUNNELS = 0x01F0, // Установка туннелей реплеев
    W3GS_OUTGOING_SWITCHSETREPLAYTUNNELS_OTHERS = 0x01F1, // Другие игроки устанавливают туннели
    W3GS_OUTGOING_SWITCHGETREPLAYTUNNELS = 0x01F2, // Получение туннелей реплеев
    W3GS_OUTGOING_SWITCHGETREPLAYTUNNELS_OTHERS = 0x01F3, // Другие игроки получают туннели
    W3GS_OUTGOING_SWITCHSETREPLAYVPN = 0x01F4, // Установка VPN реплея
    W3GS_OUTGOING_SWITCHSETREPLAYVPN_OTHERS = 0x01F5, // Другие игроки устанавливают VPN
    W3GS_OUTGOING_SWITCHGETREPLAYVPN = 0x01F6, // Получение VPN реплея
    W3GS_OUTGOING_SWITCHGETREPLAYVPN_OTHERS = 0x01F7, // Другие игроки получают VPN
    W3GS_OUTGOING_SWITCHSETREPLAYVPNS = 0x01F8, // Установка VPN реплеев
    W3GS_OUTGOING_SWITCHSETREPLAYVPNS_OTHERS = 0x01F9, // Другие игроки устанавливают VPN
    W3GS_OUTGOING_SWITCHGETREPLAYVPNS = 0x01FA, // Получение VPN реплеев
    W3GS_OUTGOING_SWITCHGETREPLAYVPNS_OTHERS = 0x01FB, // Другие игроки получают VPN
    W3GS_OUTGOING_SWITCHSETREPLAYPROXY = 0x01FC, // Установка прокси реплея
    W3GS_OUTGOING_SWITCHSETREPLAYPROXY_OTHERS = 0x01FD, // Другие игроки устанавливают прокси
    W3GS_OUTGOING_SWITCHGETREPLAYPROXY = 0x01FE, // Получение прокси реплея
    W3GS_OUTGOING_SWITCHGETREPLAYPROXY_OTHERS = 0x01FF, // Другие игроки получают прокси
    W3GS_OUTGOING_SWITCHSETREPLAYPROXIES = 0x0200, // Установка прокси реплеев
    W3GS_OUTGOING_SWITCHSETREPLAYPROXIES_OTHERS = 0x0201, // Другие игроки устанавливают прокси
    W3GS_OUTGOING_SWITCHGETREPLAYPROXIES = 0x0202, // Получение прокси реплеев
    W3GS_OUTGOING_SWITCHGETREPLAYPROXIES_OTHERS = 0x0203, // Другие игроки получают прокси
    W3GS_OUTGOING_SWITCHSETREPLAYRELAY = 0x0204, // Установка реле реплея
    W3GS_OUTGOING_SWITCHSETREPLAYRELAY_OTHERS = 0x0205, // Другие игроки устанавливают реле
    W3GS_OUTGOING_SWITCHGETREPLAYRELAY = 0x0206, // Получение реле реплея
    W3GS_OUTGOING_SWITCHGETREPLAYRELAY_OTHERS = 0x0207, // Другие игроки получают реле
    W3GS_OUTGOING_SWITCHSETREPLAYRELAYS = 0x0208, // Установка реле реплеев
    W3GS_OUTGOING_SWITCHSETREPLAYRELAYS_OTHERS = 0x0209, // Другие игроки устанавливают реле
    W3GS_OUTGOING_SWITCHGETREPLAYRELAYS = 0x020A, // Получение реле реплеев
    W3GS_OUTGOING_SWITCHGETREPLAYRELAYS_OTHERS = 0x020B, // Другие игроки получают реле
    W3GS_OUTGOING_SWITCHSETREPLAYGATE = 0x020C, // Установка шлюза реплея
    W3GS_OUTGOING_SWITCHSETREPLAYGATE_OTHERS = 0x020D, // Другие игроки устанавливают шлюз
    W3GS_OUTGOING_SWITCHGETREPLAYGATE = 0x020E, // Получение шлюза реплея
    W3GS_OUTGOING_SWITCHGETREPLAYGATE_OTHERS = 0x020F, // Другие игроки получают шлюз
    W3GS_OUTGOING_SWITCHSETREPLAYGATES = 0x0210, // Установка шлюзов реплеев
    W3GS_OUTGOING_SWITCHSETREPLAYGATES_OTHERS = 0x0211, // Другие игроки устанавливают шлюзы
    W3GS_OUTGOING_SWITCHGETREPLAYGATES = 0x0212, // Получение шлюзов реплеев
    W3GS_OUTGOING_SWITCHGETREPLAYGATES_OTHERS = 0x0213, // Другие игроки получают шлюзы
    W3GS_OUTGOING_SWITCHSETREPLAYFIREWALL = 0x0214, // Установка фаервола реплея
    W3GS_OUTGOING_SWITCHSETREPLAYFIREWALL_OTHERS = 0x0215, // Другие игроки устанавливают фаервол
    W3GS_OUTGOING_SWITCHGETREPLAYFIREWALL = 0x0216, // Получение фаервола реплея
    W3GS_OUTGOING_SWITCHGETREPLAYFIREWALL_OTHERS = 0x0217, // Другие игроки получают фаервол
    W3GS_OUTGOING_SWITCHSETREPLAYFIREWALLS = 0x0218, // Установка фаерволов реплеев
    W3GS_OUTGOING_SWITCHSETREPLAYFIREWALLS_OTHERS = 0x0219, // Другие игроки устанавливают фаерволы
    W3GS_OUTGOING_SWITCHGETREPLAYFIREWALLS = 0x021A, // Получение фаерволов реплеев
    W3GS_OUTGOING_SWITCHGETREPLAYFIREWALLS_OTHERS = 0x021B, // Другие игроки получают фаерволы
    W3GS_OUTGOING_SWITCHSETREPLAYNAT = 0x021C, // Установка NAT реплея
    W3GS_OUTGOING_SWITCHSETREPLAYNAT_OTHERS = 0x021D, // Другие игроки устанавливают NAT
    W3GS_OUTGOING_SWITCHGETREPLAYNAT = 0x021E, // Получение NAT реплея
    W3GS_OUTGOING_SWITCHGETREPLAYNAT_OTHERS = 0x021F, // Другие игроки получают NAT
    W3GS_OUTGOING_SWITCHSETREPLAYNATS = 0x0220, // Установка NAT реплеев
    W3GS_OUTGOING_SWITCHSETREPLAYNATS_OTHERS = 0x0221, // Другие игроки устанавливают NAT
    W3GS_OUTGOING_SWITCHGETREPLAYNATS = 0x0222, // Получение NAT реплеев
    W3GS_OUTGOING_SWITCHGETREPLAYNATS_OTHERS = 0x0223, // Другие игроки получают NAT
    W3GS_OUTGOING_SWITCHSETREPLAYDMZ = 0x0224, // Установка DMZ реплея
    W3GS_OUTGOING_SWITCHSETREPLAYDMZ_OTHERS = 0x0225, // Другие игроки устанавливают DMZ
    W3GS_OUTGOING_SWITCHGETREPLAYDMZ = 0x0226, // Получение DMZ реплея
    W3GS_OUTGOING_SWITCHGETREPLAYDMZ_OTHERS = 0x0227, // Другие игроки получают DMZ
    W3GS_OUTGOING_SWITCHSETREPLAYDMZS = 0x0228, // Установка DMZ реплеев
    W3GS_OUTGOING_SWITCHSETREPLAYDMZS_OTHERS = 0x0229, // Другие игроки устанавливают DMZ
    W3GS_OUTGOING_SWITCHGETREPLAYDMZS = 0x022A, // Получение DMZ реплеев
    W3GS_OUTGOING_SWITCHGETREPLAYDMZS_OTHERS = 0x022B, // Другие игроки получают DMZ
    W3GS_OUTGOING_SWITCHSETREPLAYROUTE = 0x022C, // Установка маршрута реплея
    W3GS_OUTGOING_SWITCHSETREPLAYROUTE_OTHERS = 0x022D, // Другие игроки устанавливают маршрут
    W3GS_OUTGOING_SWITCHGETREPLAYROUTE = 0x022E, // Получение маршрута реплея
    W3GS_OUTGOING_SWITCHGETREPLAYROUTE_OTHERS = 0x022F, // Другие игроки получают маршрут
    W3GS_OUTGOING_SWITCHSETREPLAYROUTES = 0x0230, // Установка маршрутов реплеев
    W3GS_OUTGOING_SWITCHSETREPLAYROUTES_OTHERS = 0x0231, // Другие игроки устанавливают маршруты
    W3GS_OUTGOING_SWITCHGETREPLAYROUTES = 0x0232, // Получение маршрутов реплеев
    W3GS_OUTGOING_SWITCHGETREPLAYROUTES_OTHERS = 0x0233, // Другие игроки получают маршруты
    W3GS_OUTGOING_SWITCHSETREPLAYSUBNET = 0x0234, // Установка подсети реплея
    W3GS_OUTGOING_SWITCHSETREPLAYSUBNET_OTHERS = 0x0235, // Другие игроки устанавливают подсеть
    W3GS_OUTGOING_SWITCHGETREPLAYSUBNET = 0x0236, // Получение подсети реплея
    W3GS_OUTGOING_SWITCHGETREPLAYSUBNET_OTHERS = 0x0237, // Другие игроки получают подсеть
    W3GS_OUTGOING_SWITCHSETREPLAYSUBNETS = 0x0238, // Установка подсетей реплеев
    W3GS_OUTGOING_SWITCHSETREPLAYSUBNETS_OTHERS = 0x0239, // Другие игроки устанавливают подсети
    W3GS_OUTGOING_SWITCHGETREPLAYSUBNETS = 0x023A, // Получение подсетей реплеев
    W3GS_OUTGOING_SWITCHGETREPLAYSUBNETS_OTHERS = 0x023B, // Другие игроки получают подсети
    W3GS_OUTGOING_SWITCHSETREPLAYMASK = 0x023C, // Установка маски реплея
    W3GS_OUTGOING_SWITCHSETREPLAYMASK_OTHERS = 0x023D, // Другие игроки устанавливают маску
    W3GS_OUTGOING_SWITCHGETREPLAYMASK = 0x023E, // Получение маски реплея
    W3GS_OUTGOING_SWITCHGETREPLAYMASK_OTHERS = 0x023F, // Другие игроки получают маску
    W3GS_OUTGOING_SWITCHSETREPLAYMASKS = 0x0240, // Установка масок реплеев
    W3GS_OUTGOING_SWITCHSETREPLAYMASKS_OTHERS = 0x0241, // Другие игроки устанавливают маски
    W3GS_OUTGOING_SWITCHGETREPLAYMASKS = 0x0242, // Получение масок реплеев
    W3GS_OUTGOING_SWITCHGETREPLAYMASKS_OTHERS = 0x0243, // Другие игроки получают маски
    W3GS_OUTGOING_SWITCHSETREPLAYNETWORK = 0x0244, // Установка сети реплея
    W3GS_OUTGOING_SWITCHSETREPLAYNETWORK_OTHERS = 0x0245, // Другие игроки устанавливают сеть
    W3GS_OUTGOING_SWITCHGETREPLAYNETWORK = 0x0246, // Получение сети реплея
    W3GS_OUTGOING_SWITCHGETREPLAYNETWORK_OTHERS = 0x0247, // Другие игроки получают сеть
    W3GS_OUTGOING_SWITCHSETREPLAYNETWORKS = 0x0248, // Установка сетей реплеев
    W3GS_OUTGOING_SWITCHSETREPLAYNETWORKS_OTHERS = 0x0249, // Другие игроки устанавливают сети
    W3GS_OUTGOING_SWITCHGETREPLAYNETWORKS = 0x024A, // Получение сетей реплеев
    W3GS_OUTGOING_SWITCHGETREPLAYNETWORKS_OTHERS = 0x024B, // Другие игроки получают сети
    W3GS_OUTGOING_SWITCHSETREPLAYINTERFACE = 0x024C, // Установка интерфейса реплея
    W3GS_OUTGOING_SWITCHSETREPLAYINTERFACE_OTHERS = 0x024D, // Другие игроки устанавливают интерфейс
    W3GS_OUTGOING_SWITCHGETREPLAYINTERFACE = 0x024E, // Получение интерфейса реплея
    W3GS_OUTGOING_SWITCHGETREPLAYINTERFACE_OTHERS = 0x024F, // Другие игроки получают интерфейс
    W3GS_OUTGOING_SWITCHSETREPLAYINTERFACES = 0x0250, // Установка интерфейсов реплеев
    W3GS_OUTGOING_SWITCHSETREPLAYINTERFACES_OTHERS = 0x0251, // Другие игроки устанавливают интерфейсы
    W3GS_OUTGOING_SWITCHGETREPLAYINTERFACES = 0x0252, // Получение интерфейсов реплеев
    W3GS_OUTGOING_SWITCHGETREPLAYINTERFACES_OTHERS = 0x0253, // Другие игроки получают интерфейсы
    W3GS_OUTGOING_SWITCHSETREPLAYADAPTER = 0x0254, // Установка адаптера реплея
    W3GS_OUTGOING_SWITCHSETREPLAYADAPTER_OTHERS = 0x0255, // Другие игроки устанавливают адаптер
    W3GS_OUTGOING_SWITCHGETREPLAYADAPTER = 0x0256, // Получение адаптера реплея
    W3GS_OUTGOING_SWITCHGETREPLAYADAPTER_OTHERS = 0x0257, // Другие игроки получают адаптер
    W3GS_OUTGOING_SWITCHSETREPLAYADAPTERS = 0x0258, // Установка адаптеров реплеев
    W3GS_OUTGOING_SWITCHSETREPLAYADAPTERS_OTHERS = 0x0259, // Другие игроки устанавливают адаптеры
    W3GS_OUTGOING_SWITCHGETREPLAYADAPTERS = 0x025A, // Получение адаптеров реплеев
    W3GS_OUTGOING_SWITCHGETREPLAYADAPTERS_OTHERS = 0x025B, // Другие игроки получают адаптеры
    W3GS_OUTGOING_SWITCHSETREPLAYDEVICE = 0x025C, // Установка устройства реплея
    W3GS_OUTGOING_SWITCHSETREPLAYDEVICE_OTHERS = 0x025D, // Другие игроки устанавливают устройство
    W3GS_OUTGOING_SWITCHGETREPLAYDEVICE = 0x025E, // Получение устройства реплея
    W3GS_OUTGOING_SWITCHGETREPLAYDEVICE_OTHERS = 0x025F, // Другие игроки получают устройство
    W3GS_OUTGOING_SWITCHSETREPLAYDEVICES = 0x0260, // Установка устройств реплеев
    W3GS_OUTGOING_SWITCHSETREPLAYDEVICES_OTHERS = 0x0261, // Другие игроки устанавливают устройства
    W3GS_OUTGOING_SWITCHGETREPLAYDEVICES = 0x0262, // Получение устройств реплеев
    W3GS_OUTGOING_SWITCHGETREPLAYDEVICES_OTHERS = 0x0263, // Другие игроки получают устройства
    W3GS_OUTGOING_SWITCHSETREPLAYDRIVER = 0x0264, // Установка драйвера реплея
    W3GS_OUTGOING_SWITCHSETREPLAYDRIVER_OTHERS = 0x0265, // Другие игроки устанавливают драйвер
    W3GS_OUTGOING_SWITCHGETREPLAYDRIVER = 0x0266, // Получение драйвера реплея
    W3GS_OUTGOING_SWITCHGETREPLAYDRIVER_OTHERS = 0x0267, // Другие игроки получают драйвер
    W3GS_OUTGOING_SWITCHSETREPLAYDRIVERS = 0x0268, // Установка драйверов реплеев
    W3GS_OUTGOING_SWITCHSETREPLAYDRIVERS_OTHERS = 0x0269, // Другие игроки устанавливают драйверы
    W3GS_OUTGOING_SWITCHGETREPLAYDRIVERS = 0x026A, // Получение драйверов реплеев
    W3GS_OUTGOING_SWITCHGETREPLAYDRIVERS_OTHERS = 0x026B, // Другие игроки получают драйверы
    W3GS_OUTGOING_SWITCHSETREPLAYMODULE = 0x026C, // Установка модуля реплея
    W3GS_OUTGOING_SWITCHSETREPLAYMODULE_OTHERS = 0x026D, // Другие игроки устанавливают модуль
    W3GS_OUTGOING_SWITCHGETREPLAYMODULE = 0x026E, // Получение модуля реплея
    W3GS_OUTGOING_SWITCHGETREPLAYMODULE_OTHERS = 0x026F, // Другие игроки получают модуль
    W3GS_OUTGOING_SWITCHSETREPLAYMODULES = 0x0270, // Установка модулей реплеев
    W3GS_OUTGOING_SWITCHSETREPLAYMODULES_OTHERS = 0x0271, // Другие игроки устанавливают модули
    W3GS_OUTGOING_SWITCHGETREPLAYMODULES = 0x0272, // Получение модулей реплеев
    W3GS_OUTGOING_SWITCHGETREPLAYMODULES_OTHERS = 0x0273, // Другие игроки получают модули
    W3GS_OUTGOING_SWITCHSETREPLAYLIBRARY = 0x0274, // Установка библиотеки реплея
    W3GS_OUTGOING_SWITCHSETREPLAYLIBRARY_OTHERS = 0x0275, // Другие игроки устанавливают библиотеку
    W3GS_OUTGOING_SWITCHGETREPLAYLIBRARY = 0x0276, // Получение библиотеки реплея
    W3GS_OUTGOING_SWITCHGETREPLAYLIBRARY_OTHERS = 0x0277, // Другие игроки получают библиотеку
    W3GS_OUTGOING_SWITCHSETREPLAYLIBRARIES = 0x0278, // Установка библиотек реплеев
    W3GS_OUTGOING_SWITCHSETREPLAYLIBRARIES_OTHERS = 0x0279, // Другие игроки устанавливают библиотеки
    W3GS_OUTGOING_SWITCHGETREPLAYLIBRARIES = 0x027A, // Получение библиотек реплеев
    W3GS_OUTGOING_SWITCHGETREPLAYLIBRARIES_OTHERS = 0x027B, // Другие игроки получают библиотеки
    W3GS_OUTGOING_SWITCHSETREPLAYPLUGIN = 0x027C, // Установка плагина реплея
    W3GS_OUTGOING_SWITCHSETREPLAYPLUGIN_OTHERS = 0x027D, // Другие игроки устанавливают плагин
    W3GS_OUTGOING_SWITCHGETREPLAYPLUGIN = 0x027E, // Получение плагина реплея
    W3GS_OUTGOING_SWITCHGETREPLAYPLUGIN_OTHERS = 0x027F, // Другие игроки получают плагин
    W3GS_OUTGOING_SWITCHSETREPLAYPLUGINS = 0x0280, // Установка плагинов реплеев
    W3GS_OUTGOING_SWITCHSETREPLAYPLUGINS_OTHERS = 0x0281, // Другие игроки устанавливают плагины
    W3GS_OUTGOING_SWITCHGETREPLAYPLUGINS = 0x0282, // Получение плагинов реплеев
    W3GS_OUTGOING_SWITCHGETREPLAYPLUGINS_OTHERS = 0x0283, // Другие игроки получают плагины
    W3GS_OUTGOING_SWITCHSETREPLAYEXTENSION = 0x0284, // Установка расширения реплея
    W3GS_OUTGOING_SWITCHSETREPLAYEXTENSION_OTHERS = 0x0285, // Другие игроки устанавливают расширение
    W3GS_OUTGOING_SWITCHGETREPLAYEXTENSION = 0x0286, // Получение расширения реплея
    W3GS_OUTGOING_SWITCHGETREPLAYEXTENSION_OTHERS = 0x0287, // Другие игроки получают расширение
    W3GS_OUTGOING_SWITCHSETREPLAYEXTENSIONS = 0x0288, // Установка расширений реплеев
    W3GS_OUTGOING_SWITCHSETREPLAYEXTENSIONS_OTHERS = 0x0289, // Другие игроки устанавливают расширения
    W3GS_OUTGOING_SWITCHGETREPLAYEXTENSIONS = 0x028A, // Получение расширений реплеев
    W3GS_OUTGOING_SWITCHGETREPLAYEXTENSIONS_OTHERS = 0x028B, // Другие игроки получают расширения
    W3GS_OUTGOING_SWITCHSETREPLAYADDON = 0x028C, // Установка аддона реплея
    W3GS_OUTGOING_SWITCHSETREPLAYADDON_OTHERS = 0x028D, // Другие игроки устанавливают аддон
    W3GS_OUTGOING_SWITCHGETREPLAYADDON = 0x028E, // Получение аддона реплея
    W3GS_OUTGOING_SWITCHGETREPLAYADDON_OTHERS = 0x028F, // Другие игроки получают аддон
    W3GS_OUTGOING_SWITCHSETREPLAYADDONS = 0x0290, // Установка аддонов реплеев
    W3GS_OUTGOING_SWITCHSETREPLAYADDONS_OTHERS = 0x0291, // Другие игроки устанавливают аддоны
    W3GS_OUTGOING_SWITCHGETREPLAYADDONS = 0x0292, // Получение аддонов реплеев
    W3GS_OUTGOING_SWITCHGETREPLAYADDONS_OTHERS = 0x0293, // Другие игроки получают аддоны
    W3GS_OUTGOING_SWITCHSETREPLAYPATCH = 0x0294, // Установка патча реплея
    W3GS_OUTGOING_SWITCHSETREPLAYPATCH_OTHERS = 0x0295, // Другие игроки устанавливают патч
    W3GS_OUTGOING_SWITCHGETREPLAYPATCH = 0x0296, // Получение патча реплея
    W3GS_OUTGOING_SWITCHGETREPLAYPATCH_OTHERS = 0x0297, // Другие игроки получают патч
    W3GS_OUTGOING_SWITCHSETREPLAYPATCHES = 0x0298, // Установка патчей реплеев
    W3GS_OUTGOING_SWITCHSETREPLAYPATCHES_OTHERS = 0x0299, // Другие игроки устанавливают патчи
    W3GS_OUTGOING_SWITCHGETREPLAYPATCHES = 0x029A, // Получение патчей реплеев
    W3GS_OUTGOING_SWITCHGETREPLAYPATCHES_OTHERS = 0x029B, // Другие игроки получают патчи
    W3GS_OUTGOING_SWITCHSETREPLAYUPDATE = 0x029C, // Установка обновления реплея
    W3GS_OUTGOING_SWITCHSETREPLAYUPDATE_OTHERS = 0x029D, // Другие игроки устанавливают обновление
    W3GS_OUTGOING_SWITCHGETREPLAYUPDATE = 0x029E, // Получение обновления реплея
    W3GS_OUTGOING_SWITCHGETREPLAYUPDATE_OTHERS = 0x029F, // Другие игроки получают обновление
    W3GS_OUTGOING_SWITCHSETREPLAYUPDATES = 0x02A0, // Установка обновлений реплеев
    W3GS_OUTGOING_SWITCHSETREPLAYUPDATES_OTHERS = 0x02A1, // Другие игроки устанавливают обновления
    W3GS_OUTGOING_SWITCHGETREPLAYUPDATES = 0x02A2, // Получение обновлений реплеев
    W3GS_OUTGOING_SWITCHGETREPLAYUPDATES_OTHERS = 0x02A3, // Другие игроки получают обновления
    W3GS_OUTGOING_SWITCHSETREPLAYVERSION = 0x02A4, // Установка версии реплея
    W3GS_OUTGOING_SWITCHSETREPLAYVERSION_OTHERS = 0x02A5, // Другие игроки устанавливают версию
    W3GS_OUTGOING_SWITCHGETREPLAYVERSION = 0x02A6, // Получение версии реплея
    W3GS_OUTGOING_SWITCHGETREPLAYVERSION_OTHERS = 0x02A7, // Другие игроки получают версию
    W3GS_OUTGOING_SWITCHSETREPLAYVERSIONS = 0x02A8, // Установка версий реплеев
    W3GS_OUTGOING_SWITCHSETREPLAYVERSIONS_OTHERS = 0x02A9, // Другие игроки устанавливают версии
    W3GS_OUTGOING_SWITCHGETREPLAYVERSIONS = 0x02AA, // Получение версий реплеев
    W3GS_OUTGOING_SWITCHGETREPLAYVERSIONS_OTHERS = 0x02AB, // Другие игроки получают версии
    W3GS_OUTGOING_SWITCHSETREPLAYBUILD = 0x02AC, // Установка сборки реплея
    W3GS_OUTGOING_SWITCHSETREPLAYBUILD_OTHERS = 0x02AD, // Другие игроки устанавливают сборку
    W3GS_OUTGOING_SWITCHGETREPLAYBUILD = 0x02AE, // Получение сборки реплея
    W3GS_OUTGOING_SWITCHGETREPLAYBUILD_OTHERS = 0x02AF, // Другие игроки получают сборку
    W3GS_OUTGOING_SWITCHSETREPLAYBUILDS = 0x02B0, // Установка сборок реплеев
    W3GS_OUTGOING_SWITCHSETREPLAYBUILDS_OTHERS = 0x02B1, // Другие игроки устанавливают сборки
    W3GS_OUTGOING_SWITCHGETREPLAYBUILDS = 0x02B2, // Получение сборок реплеев
    W3GS_OUTGOING_SWITCHGETREPLAYBUILDS_OTHERS = 0x02B3, // Другие игроки получают сборки
    W3GS_OUTGOING_SWITCHSETREPLAYREVISION = 0x02B4, // Установка ревизии реплея
    W3GS_OUTGOING_SWITCHSETREPLAYREVISION_OTHERS = 0x02B5, // Другие игроки устанавливают ревизию
    W3GS_OUTGOING_SWITCHGETREPLAYREVISION = 0x02B6, // Получение ревизии реплея
    W3GS_OUTGOING_SWITCHGETREPLAYREVISION_OTHERS = 0x02B7, // Другие игроки получают ревизию
    W3GS_OUTGOING_SWITCHSETREPLAYREVISIONS = 0x02B8, // Установка ревизий реплеев
    W3GS_OUTGOING_SWITCHSETREPLAYREVISIONS_OTHERS = 0x02B9, // Другие игроки устанавливают ревизии
    W3GS_OUTGOING_SWITCHGETREPLAYREVISIONS = 0x02BA, // Получение ревизий реплеев
    W3GS_OUTGOING_SWITCHGETREPLAYREVISIONS_OTHERS = 0x02BB, // Другие игроки получают ревизии
    W3GS_OUTGOING_SWITCHSETREPLAYCHANGELIST = 0x02BC, // Установка списка изменений реплея
    W3GS_OUTGOING_SWITCHSETREPLAYCHANGELIST_OTHERS = 0x02BD, // Другие игроки устанавливают список изменений
    W3GS_OUTGOING_SWITCHGETREPLAYCHANGELIST = 0x02BE, // Получение списка изменений реплея
    W3GS_OUTGOING_SWITCHGETREPLAYCHANGELIST_OTHERS = 0x02BF, // Другие игроки получают список изменений
    W3GS_OUTGOING_SWITCHSETREPLAYCHANGELISTS = 0x02C0, // Установка списков изменений реплеев
    W3GS_OUTGOING_SWITCHSETREPLAYCHANGELISTS_OTHERS = 0x02C1, // Другие игроки устанавливают списки изменений
    W3GS_OUTGOING_SWITCHGETREPLAYCHANGELISTS = 0x02C2, // Получение списков изменений реплеев
    W3GS_OUTGOING_SWITCHGETREPLAYCHANGELISTS_OTHERS = 0x02C3, // Другие игроки получают списки изменений
    W3GS_OUTGOING_SWITCHSETREPLAYBRANCH = 0x02C4, // Установка ветки реплея
    W3GS_OUTGOING_SWITCHSETREPLAYBRANCH_OTHERS = 0x02C5, // Другие игроки устанавливают ветку
    W3GS_OUTGOING_SWITCHGETREPLAYBRANCH = 0x02C6, // Получение ветки реплея
    W3GS_OUTGOING_SWITCHGETREPLAYBRANCH_OTHERS = 0x02C7, // Другие игроки получают ветку
    W3GS_OUTGOING_SWITCHSETREPLAYBRANCHES = 0x02C8, // Установка веток реплеев
    W3GS_OUTGOING_SWITCHSETREPLAYBRANCHES_OTHERS = 0x02C9, // Другие игроки устанавливают ветки
    W3GS_OUTGOING_SWITCHGETREPLAYBRANCHES = 0x02CA, // Получение веток реплеев
    W3GS_OUTGOING_SWITCHGETREPLAYBRANCHES_OTHERS = 0x02CB, // Другие игроки получают ветки
};